POST http://localhost:5000/api/salads/ HTTP/1.1
Content-Type: application/json

{
    "name": "SomeSalad",
    "weight": 1.0,
    "ingredients": ["bread", "milk"],
    "sauce": "none",
    "dietType": "none",
    "spicy": false,
    "expired": "2023-12-12"
}

