POST http://localhost:5000/api/salads/ HTTP/1.1
Content-Type: application/json

{
    "name": "NewSalad",
    "weight": 1.0,
    "ingredients": ["potato", "tomato", "chicken"],
    "sauce": "mayo",
    "dietType": "none",
    "spicy": false,
    "expired": "2023-12-12"
}

