POST http://localhost:5000/ HTTP/1.1
Content-Type: application/json

{
    "name": "Caesar",
    "weight": 1.0,
    "ingredients": ["chicken", "salad", "bread"],
    "sauce": "mayonnaise",
    "dietType": "none",
    "spicy": false,
    "expired": "2022-12-12"
}

